import { Metric, NewsItem } from './types';

export const mockMetrics: Metric[] = [
  { id: '1', title: 'Total Volume (MT)', value: '1,245,000', trend: 'up', percentage: '+4.2%' },
  { id: '2', title: 'Active AZK Stations', value: '142', trend: 'up', percentage: '+2' },
  { id: '3', title: 'Avg. Profit Margin', value: '14.5%', trend: 'neutral', percentage: '0.0%' },
  { id: '4', title: 'Supply Chain Delay', value: '1.2 days', trend: 'down', percentage: '-0.4d' },
];

export const mockNews: NewsItem[] = [
  {
    id: '1',
    title: 'Navarro Trade — Алматы өңіріндегі сенімді отын жеткізушісі',
    date: '2026 M06 12',
    summary: '«Navarro Trade» ЖШС — Алматы өңіріндегі жанар-жағармай материалдарын көтерме жеткізу нарығындағы көшбасшы және сенімді серіктес. Біз клиенттерімізге жоғары сапалы АИ-92, АИ-95 автобензиндерін, экологиялық таза жазғы және қысқы дизель отынын, сондай-ақ халықаралық стандарттарға сай келетін JET A-1 авиациялық керосинін ұсынамыз.\n\nБіздің негізгі артықшылықтарымыз:\n• Сәйкестік сертификаттарымен расталған отынның кепілді сапасы;\n• Меншікті заманауи және қауіпсіз бензовоз автопаркі арқылы жедел жеткізу;\n• Тікелей мұнай өңдеу зауыттарынан (МӨЗ) отын тасымалдау есебінен икемді баға саясаты;\n• Кәсіби мамандар командасы және тәулік бойы жұмыс істейтін қолдау қызметі.\n\n«Navarro Trade» компаниясы жылдар бойы жинаған тәжірибесі мен тұрақты серіктестік қатынастарының арқасында ірі өнеркәсіптік кәсіпорындардың, жеке жанармай құю станциялары желілерінің және транспорттық-логистикалық хабтардың қажеттіліктерін толық өтей алады. Біз әрқашан уақтылы жеткізілім мен жоғары қызмет көрсету деңгейіне кепілдік береміз!',
    category: 'Logistics',
    imageUrl: '/src/assets/images/navarro_trade_selfie_1781524379837.jpg',
    titleTranslations: {
      kz: 'Navarro Trade — Алматы өңіріндегі сенімді отын жеткізушісі',
      ru: 'Navarro Trade — надежный поставщик топлива в Алматинском регионе',
      en: 'Navarro Trade — Trusted Fuel Supplier in Almaty Region'
    },
    summaryTranslations: {
      kz: '«Navarro Trade» ЖШС — Алматы өңіріндегі жанар-жағармай материалдарын көтерме жеткізу нарығындағы көшбасшы және сенімді серіктес. Біз клиенттерімізге жоғары сапалы АИ-92, АИ-95 автобензиндерін, экологиялық таза жазғы және қысқы дизель отынын, сондай-ақ халықаралық стандарттарға сай келетін JET A-1 авиациялық керосинін ұсынамыз.\n\nБіздің негізгі артықшылықтарымыз:\n• Сәйкестік сертификаттарымен расталған отынның кепілді сапасы;\n• Меншікті заманауи және қауіпсіз бензовоз автопаркі арқылы жедел жеткізу;\n• Тікелей мұнай өңдеу зауыттарынан (МӨЗ) отын тасымалдау есебінен икемді баға саясаты;\n• Кәсіби мамандар командасы және тәулік бойы жұмыс істейтін қолдау қызметі.\n\n«Navarro Trade» компаниясы жылдар бойы жинаған тәжірибесі мен тұрақты серіктестік қатынастарының арқасында ірі өнеркәсіптік кәсіпорындардың, жеке жанармай құю станциялары желілерінің және транспорттық-логистикалық хабтардың қажеттіліктерін толық өтей алады. Біз әрқашан уақтылы жеткізілім мен жоғары қызмет көрсету деңгейіне кепілдік береміз!',
      ru: 'ТОО «Navarro Trade» является одним из признанных лидеров в сфере оптовых поставок нефтепродуктов в Алматы и Алматинской области. Наша специализация — комплексное обеспечение бизнеса высококачественным топливом, включая бензин марок АИ-92, АИ-95, экологичное дизельное топливо (летнее и зимнее), а также сертифицированное авиационное топливо марок JET A-1 и ТС-1 / РТ.\n\nНаши ключевые преимущества:\n• Безупречное качество топлива напрямую от ведущих нефтеперерабатывающих заводов (НПЗ);\n• Наличие собственного парка современных бензовозов, оснащенных GPS-мониторингом и системами безопасности;\n• Проработанные логистические цепочки для бесперебойного снабжения в рекордные сроки;\n• Выгодное ценообразование и персональные условия сотрудничества для постоянных партнеров.\n\nЗа годы активной деятельности компания заслужила безупречную репутацию среди промышленных предприятий, частных сетей АЗС и авиационных операторов Казахстана. Выбирая «Navarro Trade», вы получаете стабильность, безопасность и высокий уровень сервиса на каждом этапе поставки!',
      en: 'Navarro Trade LLP is a leading player in the wholesale distribution of premium petroleum products across Almaty and southern Kazakhstan. We offer high-quality gasoline (AI-92, AI-95), environmentally safe summer and winter diesel fuel, and aviation-grade kerosene conforming to international criteria (JET A-1, TS-1, and RT).\n\nWhy clients choose us:\n• Direct partnership with top refineries ensures impeccable fuel quality and compliance;\n• Own fleet of state-of-the-art fuel tankers operated under rigorous security guidelines;\n• Advanced GPS tracking and real-time logistics management for punctual deliveries;\n• Tailored wholesale pricing options and robust commercial terms.\n\nNavarro Trade is widely recognized as a dependable fuel provider for industrial complexes, retail gas station networks, and transportation conglomerates. We stand ready to power your business operations with our unmatched logistics capabilities!'
    }
  },
  {
    id: '2',
    title: 'Жаңа мұнай базасының іске қосылуы — Алматы облысы',
    date: '2026 M06 9',
    summary: 'Алматы облысында сыйымдылығы 24 000 тонналық заманауи, жоғары технологиялық жаңа мұнай базасының ресми ашылуы өтті. Бұл нысан аймақтағы энергетикалық қауіпсіздікті нығайту және жанар-жағармай қорларын тұрақтандыру жолындағы маңызды қадам болып табылады.\n\nЖаңа мұнай базасының ерекшеліктері:\n1. Өлшеу жүйелері (АСКУН): Сұйықтықтың көлемі мен массасын нақты уақыт режимінде өлшейтін автоматты электронды құрылғылар орнатылған.\n2. Жоғары жылдамдықты сорғылар: Отын депосына өнімдерді жедел құю және ағызу мүмкіндігі.\n3. Заманауи зертхана: Мұнай өнімдерінің сапасын келу сәтінен бастап жөнелтуге дойін бақылайтын аккредиттелген химиялық талдау зертханасы.\n4. Қауіпсіздік жүйесі: Өртке қарсы автоматты көбікпен сөндіру және бейнебақылау құрылғылары.\n\nБұл жоба тек қосымша жұмыс орындарын ашып қана қоймай, сонымен қатар Алматы мен Алматы облысындағы жанар-жағармай жеткізу желісінің тиімділігін айтарлықтай арттыруға мүмкіндік береді.',
    category: 'Operational',
    imageUrl: '/src/assets/images/almaty_oil_depot_aerial_1781524403784.jpg',
    titleTranslations: {
      kz: 'Жаңа мұнай базасының іске қосылуы — Алматы облысы',
      ru: 'Запуск новой нефтебазы — Алматинская область',
      en: 'Launch of a New Oil Depot — Almaty Region'
    },
    summaryTranslations: {
      kz: 'Алматы облысында сыйымдылығы 24 000 тонналық заманауи, жоғары технологиялық жаңа мұнай базасының ресми ашылуы өтті. Бұл нысан аймақтағы энергетикалық қауіпсіздікті нығайту және жанар-жағармай қорларын тұрақтандыру жолындағы маңызды қадам болып табылады.\n\nЖаңа мұнай базасының ерекшеліктері:\n1. Өлшеу жүйелері (АСКУН): Сұйықтықтың көлемі мен массасын нақты уақыт режимінде өлшейтін автоматты электронды құрылғылар орнатылған.\n2. Жоғары жылдамдықты сорғылар: Отын депосына өнімдерді жедел құю және ағызу мүмкіндігі.\n3. Заманауи зертхана: Мұнай өнімдерінің сапасын келу сәтінен бастап жөнелтуге дейін бақылайтын аккредиттелген химиялық талдау зертханасы.\n4. Қауіпсіздік жүйесі: Өртке қарсы автоматты көбікпен сөндіру және бейнебақылау құрылғылары.\n\nБұл жоба тек қосымша жұмыс орындарын ашып қана қоймай, сонымен қатар Алматы мен Алматы облысындағы жанар-жағармай жеткізу желісінің тиімділігін айтарлықтай арттыруға мүмкіндік береді.',
      ru: 'Состоялся официальный коммерческий запуск нового, высокотехнологичного нефтехранилища в Алматинской области общей полезной емкостью 24 000 тонн. Данный стратегический объект призван обеспечить долгосрочную стабильность поставок и диверсификацию резервного парка нефтепродуктов в регионе.\n\nПреимущества нового терминала:\n1. Полная автоматизация (АСКУН): Высокоточные бесконтактные радары и массовые расходомеры гарантируют стопроцентный учет объема принимаемого и отпускаемого топлива в реальном времени.\n2. Экологические стандарты: Резервуары имеют двойные стенки и современные дыхательные клапаны с улавливанием легких фракций углеводородов.\n3. Высокая производительность: Современный наливной терминал позволяет одновременно загружать до 8 бензовозов.\n4. Контроль качества: Собственная лаборатория проводит детальный экспресс-анализ каждой поступающей партии топлива.\n\nВвод терминала в эксплуатацию создает новые рабочие места, снижает логистические издержки и гарантирует бесперебойную заправку техники в пиковые сезоны!',
      en: 'We are proud to announce the official launch of our state-of-the-art petroleum storage depot in the Almaty region, featuring a total active capacity of 24,000 tons. This modern terminal marks a significant milestone in regional energy security and supply chain flexibility.\n\nKey features of the new depot:\n1. Automated Metering Systems (AMIS): High-precision electronic level gauges and mass flowmeters monitor inventory levels in real-time with absolute precision.\n2. Advanced Loading Terminal: Multi-lane high-speed pump stations allow simultaneous loading and unloading of up to 8 fuel trucks.\n3. Certified Chemical Laboratory: On-site testing facility verifies critical properties of incoming and outgoing fuel batches to maintain peak product quality.\n4. Safety and Fire Protection: Automated foam-sprinkler systems and complete thermal monitoring ensure compliance with top industrial safety protocols.\n\nThis capital investment will substantially optimize our logistics and provide unmatched supply reliability to our commercial clients.'
    }
  },
  {
    id: '3',
    title: 'JET A-1 авиакеросинін Алматы әуежайына жеткізу басталды',
    date: '2026 M06 6',
    summary: '«Navarro Trade» авиациялық қауіпсіздік пен сапаның ең жоғары деңгейін көрсете отырып, Алматы халықаралық әуежайына JET A-1 авиакеросинін тікелей жеткізу бағдарламасын сәтті іске қосты. Жеткізілетін отын халықаралық ASTM D1655 және JIG (Joint Inspection Group) спецификацияларына толық сәйкес келеді.\n\nАвиаотын тасымалының негізгі аспектілері:\n• Тасымалдаудың қауіпсіздігі: Барлық авиакеросинді тасымалдағыштар арнайы жабдықталған және ішкі сүзгілеу жүйелерімен қамтамасыз етілген;\n• Техникалық бақылау: Отынның әрбір партиясы тиеу алдында және әуежай терминалында қабылдау кезінде бірнеше сатылы зертханалық сынақтан өтеді;\n• Тұрақты қор: Мұнай базамызда тікелей Алматы әуежайына жедел жөнелту үшін тұрақты авиаотын қоры ұсталады.\n\nБұл қадам отандық және шетелдік авиакомпанияларға ең жоғары сапалы отынды бәсекелестік бағамен уақтылы алуға мүмкіндік береді, сондай-ақ Алматы әуежайының транзиттік әлеуетін арттырады.',
    category: 'Aviation',
    imageUrl: '/src/assets/images/jet_fuel_airplane_1781524423622.jpg',
    titleTranslations: {
      kz: 'JET A-1 авиакеросинін Алматы әуежайына жеткізу басталды',
      ru: 'Начались поставки авиакеросина JET A-1 в аэропорт Алматы',
      en: 'Deliveries of JET A-1 Jet Fuel to Almaty Airport Commenced'
    },
    summaryTranslations: {
      kz: '«Navarro Trade» авиациялық қауіпсіздік пен сапаның ең жоғары деңгейін көрсете отырып, Алматы халықаралық әуежайына JET A-1 авиакеросинін тікелей жеткізу бағдарламасын сәтті іске қосты. Жеткізілетін отын халықаралық ASTM D1655 және JIG (Joint Inspection Group) спецификацияларына толық сәйкес келеді.\n\nАвиаотын тасымалының негізгі аспектілері:\n• Тасымалдаудың қауіпсіздігі: Барлық авиакеросинді тасымалдағыштар арнайы жабдықталған және ішкі сүзгілеу жүйелерімен қамтамасыз етілген;\n• Техникалық бақылау: Отынның әрбір партиясы тиеу алдында және әуежай терминалында қабылдау кезінде бірнеше сатылы зертханалық сынақтан өтеді;\n• Тұрақты қор: Мұнай базамызда тікелей Алматы әуежайына жедел жөнелту үшін тұрақты авиаотын қоры ұсталады.\n\nБұл қадам отандық және шетелдік авиакомпанияларға ең жоғары сапалы отынды бәсекелестік бағамен уақтылы алуға мүмкіндік береді, сондай-ақ Алматы әуежайының транзиттік әлеуетін арттырады.',
      ru: 'Компания «Navarro Trade» рада объявить о старте регулярных прямых поставок авиационного керосина марки JET A-1 в Международный аэропорт Алматы. Наше авиационное топливо соответствует жестким глобальным требованиям ASTM D1655 и международным стандартам JIG.\n\nКлючевые детали авиационных поставок:\n• Специализированная логистика: Перевозка осуществляется выделенным автотранспортом (авиацистернами с внутренним эпоксидным покрытием для исключения коррозии);\n• Двойной контроль чистоты: Использование современных фильтров-коагуляторов пятого поколения для удаления микрочастиц влаги и механических примесей;\n• Непрерывность поставок: Постоянный неснижаемый запас топлива на терминале гарантирует заправку воздушных судов в штатном режиме даже при резком росте трафика.\n\nЗапуск этого логистического коридора повышает качество обслуживания международных авиакомпаний и укрепляет Алматинский хаб как ключевой транзитный узел между Европой и Азией.',
      en: 'Navarro Trade has officially launched direct shipments of JET A-1 aviation kerosene to Almaty International Airport. The delivered product satisfies the most stringent international benchmarks, including ASTM D1655 and JIG (Joint Inspection Group) specifications.\n\nKey highlights of our aviation fuel operations:\n• Dedicated Transport Fleet: To prevent cross-contamination, we utilize dedicated fuel tankers equipped with internal epoxy coatings and advanced water separation filters;\n• Multi-Stage Quality Inspections: Every batch undergoes certified laboratory testing at the refinery, our primary storage depot, and upon receipt at the airport tank farm;\n• Strategic Stock Reserve: We maintain dedicated bulk reserves of JET A-1 at our terminal to provide a stable, uninterrupted flow of fuel for domestic and international air carriers alike.\n\nThis milestone supports Almaty Airport\'s growing role as a crucial aviation hub linking Europe and the Asia-Pacific region.'
    }
  },
  {
    id: '4',
    title: 'SCAT Airlines — стратегиялық серіктес',
    date: '2026 M06 2',
    summary: '«Navarro Trade» ЖШС мен Қазақстанның жетекші әуе тасымалдаушыларының бірі «SCAT Airlines» арасында екі жыл мерзімге авиациялық отынды көтерме жеткізу туралы стратегиялық келісімшартқа ресми түрде қол қойылды.\n\nСеріктестік аясында келесі міндеттер атқарылады:\n1. Тұрақты жанар-жағармаймен қамту: SCAT Airlines әуе кемелерінің Алматы халықаралық әуежайындағы тұрақты және чартерлік рейстерін толықтай керосинмен уақтылы қамтамасыз ету;\n2. Сапа кепілдігі: Әрбір рейске құйылатын отынға JIG халықаралық талаптарына сәйкес бірлескен бақылау жүргізу;\n3. Логистикалық басымдық: Жедел заправкалауды қамтамасыз ету үшін арнайы техникалар мен кезексіз жеткізу желісін құру.\n\nБұл келісім екі жақтың да нарықтағы орнын нығайтады және қазақстандық жолаушылар тасымалының қауіпсіздігі мен тұрақтылығына оң әсерін тигізеді. Біз «SCAT Airlines» сеніміне жоғары баға береміз және серіктестікті дамытуға дайынбыз!',
    category: 'Aviation',
    imageUrl: '/src/assets/images/scat_airlines_terminal_1781524442477.jpg',
    titleTranslations: {
      kz: 'SCAT Airlines — стратегиялық серіктес',
      ru: 'SCAT Airlines — стратегический партнер',
      en: 'SCAT Airlines — Strategic Partner'
    },
    summaryTranslations: {
      kz: '«Navarro Trade» ЖШС мен Қазақстанның жетекші әуе тасымалдаушыларының бірі «SCAT Airlines» арасында екі жыл мерзімге авиациялық отынды көтерме жеткізу туралы стратегиялық келісімшартқа ресми түрде қол қойылды.\n\nСеріктестік аясында келесі міндеттер атқарылады:\n1. Тұрақты жанар-жағармаймен қамту: SCAT Airlines әуе кемелерінің Алматы халықаралық әуежайындағы тұрақты және чартерлік рейстерін толықтай керосинмен уақтылы қамтамасыз ету;\n2. Сапа кепілдігі: Әрбір рейске құйылатын отынға JIG халықаралық талаптарына сәйкес бірлескен бақылау жүргізу;\n3. Логистикалық басымдық: Жедел заправкалауды қамтамасыз ету үшін арнайы техникалар мен кезексіз жеткізу желісін құру.\n\nБұл келісім екі жақтың да нарықтағы орнын нығайтады және қазақстандық жолаушылар тасымалының қауіпсіздігі мен тұрақтылығына оң әсерін тигізеді. Біз «SCAT Airlines» сеніміне жоғары баға береміз және серіктестікті дамытуға дайынбыз!',
      ru: 'ТОО «Navarro Trade» и одна из крупнейших авиакомпаний Казахстана «SCAT Airlines» объявили о подписании долгосрочного соглашения о стратегическом партнерстве сроком на 2 года. В рамках контракта наша компания становится ключевым поставщиком сертифицированного авиатоплива JET A-1 для судов SCAT в Международном астропорту Алматы.\n\nПараметры соглашения включают:\n1. Бесперебойность заправки: Своевременный отпуск топлива для регулярных, международных и чартерных рейсов перевозчика;\n2. Интеграция контроля качества: Совместные комиссии будут осуществлять регулярные проверки на соответствие международным стандартам JIG на всех ступенях перевалки;\n3. Экономическая оптимизация: Долгосрочные фиксированные формулы ценообразования, гарантирующие стабильность расходов авиакомпании на топливное обеспечение.\n\nМы ценим доверие авиакомпании SCAT и уверены, что наше партнерство внесет весомый вклад в повышение доступности, пунктуальности и безопасности полетов гражданской авиации в Республике Казахстан.',
      en: 'Navarro Trade LLP is proud to announce a new two-year strategic supply agreement signed with SCAT Airlines, one of Kazakhstan\'s premier commercial air carriers. Under the terms of the agreement, Navarro Trade will serves as a primary wholesale provider of high-purity JET A-1 aviation fuel for SCAT Airlines fleet at Almaty International Airport.\n\nKey pillars of this long-term partnership include:\n1. Uncompromised Supply Continuity: Fueling of domestic, regional, and international charter flights on a strictly prioritized schedule;\n2. Joined Quality Verification: Unified procedures conforming to JIG protocols to ensure top-notch fuel purity standards before wing tank delivery;\n3. Risk Mitigation & Hedging: Flexible pricing mechanisms designed to streamline fuel operating expenditures for the carrier.\n4. Scalable Infrastructure support: Priority allocation of loading lanes and dedicated fuel trucks to reduce aircraft turnaround times.\n\nWe look forward to a successful cooperation with SCAT Airlines, continuing our devotion to flight safety and logistical excellence.'
    }
  },
  {
    id: '5',
    title: 'JIG 2 (Issue 13) стандартын енгізу аяқталды',
    date: '2026 M05 27',
    summary: 'Авиациялық операциялардың сапасын арттыру мақсатында «Navarro Trade» өзінің техникалық-технологиялық жүйелері мен мұнай базасының инфрақұрылымын халықаралық жаңа JIG 2 (Joint Inspection Group, Issue 13 - Aviation Fuel Quality Controls and Operating Standards) стандартына сәйкестендіру үрдісін сәтті аяқтады.\n\nЖүзеге асырылған негізгі өзгерістер:\n• Фильтрациялау жүйелері жаңартылды: Су бөлгіш сүзгілер мен коагуляторлар су мен ластануды толық болдырмайтын соңғы буын үлгілеріне ауыстырылды;\n• Жабдықтарды сынақтан өткізу: Барлық цистерналар, сұйықтық есептегіштер және клапандар жаңа стандарт бойынша калибрленді және сынақтан өтті;\n• Қызметкерлерді оқыту: Біздің бүкіл техникалық бригадалар мен зертхана мамандары JIG халықаралық инспекторларының қатысуымен арнайы біліктілікті арттыру курстарынан өтті.\n\nJIG 2 (Issue 13) стандартының заңды түрде енгізілуі — «Navarro Trade» отын сапасына ешқашан ымыраға келмейтінін және әрбір рейстің қауіпсіз ұшуына жоғары жауапкершілікпен қарайтынын дәлелдейді.',
    category: 'Corporate',
    imageUrl: '/src/assets/images/jig2_fuel_control_1781524466440.jpg',
    titleTranslations: {
      kz: 'JIG 2 (Issue 13) стандартын енгізу аяқталды',
      ru: 'Завершено внедрение стандартов JIG 2 (Issue 13)',
      en: 'JIG 2 (Issue 13) Standard Implementation Completed'
    },
    summaryTranslations: {
      kz: 'Авиациялық операциялардың сапасын арттыру мақсатында «Navarro Trade» өзінің техникалық-технологиялық жүйелері мен мұнай базасының инфрақұрылымын халықаралық жаңа JIG 2 (Joint Inspection Group, Issue 13 - Aviation Fuel Quality Controls and Operating Standards) стандартына сәйкестендіру үрдісін сәтті аяқтады.\n\nЖүзеге асырылған негізгі өзгерістер:\n• Фильтрациялау жүйелері жаңартылды: Су бөлгіш сүзгілер мен коагуляторлар су мен ластануды толық болдырмайтын соңғы буын үлгілеріне ауыстырылды;\n• Жабдықтарды сынақтан өткізу: Барлық цистерналар, сұйықтық есептегіштер және клапандар жаңа стандарт бойынша калибрленді және сынақтан өтті;\n• Қызметкерлерді оқыту: Біздің бүкіл техникалық бригадалар мен зертхана мамандары JIG халықаралық инспекторларының қатысуымен арнайы біліктілікті арттыру курстарынан өтті.\n\nJIG 2 (Issue 13) стандартының заңды түрде енгізілуі — «Navarro Trade» отын сапасына ешқашан ымыраға келмейтінін және әрбір рейстің қауіпсіз ұшуына жоғары жауапкершілікпен қарайтынын дәлелдейді.',
      ru: 'Компания «Navarro Trade» успешно завершила масштабную модернизацию процессов хранения, фильтрации и проведения технологических операций с авиатопливом в соответствии с новейшим изданием стандартов JIG 2 (Joint Inspection Group, Issue 13).\n\nВнедренные улучшения и стандарты:\n• Модернизация фильтров: Полное переоснащение фильтрационных установок на современные элементы, соответствующие стандарту EI 1581 / EI 1583 для предотвращения попадания следов подтоварной воды и взвесей;\n• Калибровка оборудования: Сертификация всех трубопроводов, систем заземления, аварийных клапанов и узлов учета;\n• Обучение штата: Проведена детальная переподготовка инженеров, лаборантов и водителей-аэродромных заправщиков с получением международных квалификационных сертификатов.\n\nСоответствие регламентам JIG 2 Issue 13 гарантирует международным авиационным альянсам наивысший уровень безопасности полетов и чистоты топлива при заправке "в крыло" в аэропорту.',
      en: 'To ensure top-tier flight safety, Navarro Trade has successfully completed the implementation of the globally recognized JIG 2 (Issue 13) Aviation Fuel Quality Controls and Operating Standards across all our depot and airport hydrant operations.\n\nKey updates executed under this roadmap:\n• Filter Upgrades: Installed elite water-barrier vessels and ultra-absorbent filter coalescers satisfying EI 1581 / EI 1583 mandates;\n• Precision Hardware Calibration: Recertified bulk loading valves, fuel lines, pressure differential switches, and grounding protection layouts;\n• Comprehensive Staff Accreditation: All technical personnel and laboratory chemists completed specialized training certified by JIG inspection representatives.\n\nStrict compliance with JIG 2 Issue 13 demonstrates Navarro Trade\'s absolute devotion to product integrity and zero tolerance for contamination, guaranteeing flight security and peace of mind for our valued airline partners.'
    }
  },
  {
    id: '6',
    title: 'iON жанармай желісінде жаңа АЗК ашылды',
    date: '2026 M05 21',
    summary: 'Алматы мен Қонаев (Қапшағай) қалаларын қосатын жоғары жылдамдықты күре жолдың бойында заманауи, футуристік дизайнмен жасалған жаңа «iON» автожанармай құю кешенінің (АЗК) салтанатты ашылуы өтті. Нысан «Таза қозғалыс энергиясы» (Taza qozǵalys energiasy) экологиялық тұжырымдамасы негізінде салынған.\n\nЖаңа iON станциясының мүмкіндіктері:\n• Жоғары сапалы отын: Еуро-5 стандартына сай АИ-92, АИ-95 бензиндері және Еуро-дизель тікелей «Navarro Trade» қоймасынан кедергісіз жеткізіледі;\n• Жылдам қуаттау станциясы: Электромобильдерді (EV) 20 минут ішінде 80%-ға дейін қуаттайтын соңғы үлгідегі электр зарядтағыштар;\n• Автоматтандырылған қызмет көрсету: Кезексіз төлем жасау мақсатында орнатылған заманауи өзіне-өзі қызмет көрсететін терминалдар;\n• Ыңғайлы дәмхана: Жолаушылардың демалуына арналған жайлы кафе, сергек кофе және дүкен.\n\nБутик форматындағы бұл жаңа буын АЗК эстетикалық дизайнымен және жоғары экологиялық жауапкершілігімен жол бойындағы қызмет көрсету деңгейін жаңа сатыға көтеруге бағытталған.',
    category: 'Logistics',
    imageUrl: '/src/assets/images/ion_gas_station_1781524486534.jpg',
    titleTranslations: {
      kz: 'iON жанармай желісінде жаңа АЗК ашылды',
      ru: 'Открытие новой АЗС в брендовой сети iON',
      en: 'New Smart Gas Station Opened in the iON Network'
    },
    summaryTranslations: {
      kz: 'Алматы мен Қонаев (Қапшағай) қалаларын қосатын жоғары жылдамдықты күре жолдың бойында заманауи, футуристік дизайнмен жасалған жаңа «iON» автожанармай құю кешенінің (АЗК) салтанатты ашылуы өтті. Нысан «Таза қозғалыс энергиясы» (Taza qozǵalys energiasy) экологиялық тұжырымдамасы негізінде салынған.\n\nЖаңа iON станциясының мүмкіндіктері:\n• Жоғары сапалы отын: Еуро-5 стандартына сай АИ-92, АИ-95 бензиндері және Еуро-дизель тікелей «Navarro Trade» қоймасынан кедергісіз жеткізіледі;\n• Жылдам қуаттау станциясы: Электромобильдерді (EV) 20 минут ішінде 80%-ға дейін қуаттайтын соңғы үлгідегі электр зарядтағыштар;\n• Автоматтандырылған қызмет көрсету: Кезексіз төлем жасау мақсатында орнатылған заманауи өзіне-өзі қызмет көрсететін терминалдар;\n• Ыңғайлы дәмхана: Жолаушылардың демалуына арналған жайлы кафе, сергек кофе және дүкен.\n\nБутик форматындағы бұл жаңа буын АЗК эстетикалық дизайнымен және жоғары экологиялық жауапкершілігімен жол бойындағы қызмет көрсету деңгейін жаңа сатыға көтеруге бағытталған.',
      ru: 'На скоростной автомагистрали Алматы—Конаев (Капшагай) состоялось торжественное открытие нового флагманского автозаправочного комплекса инновационной сети «iON». Станция спроектирована по уникальному футуристическому дизайну под лозунгом «Taza qozǵalys energiasy» («Энергия чистого движения»).\n\nПреимущества и сервисы нового комплекса iON:\n• Премиальное топливо Евро-5: Прямые бесперебойные поставки бензинов АИ-92, АИ-95 и ультрачистого дизельного топлива от ТОО «Navarro Trade»;\n• Сверхбыстрая зарядка электромобилей (EV): Мощные терминалы постоянного тока заряжают авто до 80% всего за 20 минут;\n• Умный ритейл и кафе: Стильный минималистичный магазин, ароматный свежий кофе и сытные закуски для комфортного отдыха водителей;\n• Цифровой терминал самообслуживания: Быстрая автоматическая оплата топлива банковскими картами и бесконтактным способом.\n\niON задает совершенно новые стандарты придорожного сервиса в Казахстане, гармонично сочетая яркий хай-тек дизайн, экологичность и максимальную заботу о клиентах!',
      en: 'A gorgeous, highly futuristic flagship filling station has been officially inaugurated along the busy Almaty—Konaev (Kashagay) high-speed expressway under the innovative brand name «iON». The complexes operate under the sustainable green philosophy «Taza qozǵalys energiasy» («Clean Motion Energy»).\n\nServices offered at the new iON terminal:\n• Premium Euro-5 Fuels: Flawless wholesale supply of AI-92, AI-95 and low-sulfur diesel fuel directly sourced from Navarro Trade depots;\n• Ultra-Fast EV Chargings: Superchargers capable of replenishing electric vehicle batteries up to 80% range in just 20 minutes;\n• Cashless Self-Service Terminals: Interactive digital touchscreeen terminals for instant automated payments;\n• Cozy Premium Cafe: Micro-bakery offering gourmet espresso, snacks, and robust retail convenience store items.\n\niON reinvents the roadside service landscape in Kazakhstan, combining futuristic architecture, eco-friendly ideals, and supreme customer comfort.'
    }
  }
];
